services:
  - type: web
    name: chatdevalor
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatdevalor-db
          property: connectionString

databases:
  - name: chatdevalor-db
    plan: free
